### PR TITLE
Adding node type to write queries based on category, and updating que…

### PR DESCRIPTION
**Pull request by PeterBaker0**
Adding node type to write queries based on category, and updating queries to use fully capitalised node labels. 

Fixes bug where user would observe empty graph responses from special upstream and downstream queries which filtered on item category.

## Migrations Required

See #55 migration - i.e. clear and rebuild prov graph.

## Feature deployment

Feature branch name: **feat-1813-special-query-fix**

URL Prefix: f1813

Pipeline links: [pipelines](https://ap-southeast-2.console.aws.amazon.com/codesuite/codepipeline/pipelines?region=ap-southeast-2&pipelines-meta=eyJmIjp7InRleHQiOiJmMTgxMyJ9LCJzIjp7InByb3BlcnR5IjoidXBkYXRlZCIsImRpcmVjdGlvbiI6LTF9LCJuIjoxMCwiaSI6MH0K)

Deployed components:

[landing-portal](https://f1813.dev.rrap-is.com/)

[job-api](https://f1813-job-api.dev.rrap-is.com/)

[data-store-api](https://f1813-data-api.dev.rrap-is.com/)

[data-store-ui](https://f1813-data.dev.rrap-is.com/)

[auth-api](https://f1813-auth-api.dev.rrap-is.com/)

[prov-api](https://f1813-prov-api.dev.rrap-is.com/)

[prov-ui](https://f1813-prov.dev.rrap-is.com/)

[registry-api](https://f1813-registry-api.dev.rrap-is.com/)

[registry-ui](https://f1813-registry.dev.rrap-is.com/)

To tear down feature deployment: ./fb destroy 1813 special-query-fix

### CODE REVIEW

**Comment by PeterBaker0** [comment]
@jyucsiro  try doing a contributing upstream datasets from here https://f1813-prov.dev.rrap-is.com/record/view?rootId=10378.1/1963953

**Comment by jyucsiro** [comment]
@PeterBaker0 cool - contributing upstream and affected downstream is working now. below - this was upstream btw...
image
image

**Comment by PeterBaker0** [comment]
@jyucsiro this should be good to go! Added unit tests. Can you approve?

**Review by jyucsiro — APPROVED** [review]
Reviewed PR via web ui. Test doing a basic count looks fine.

**Pull request merged**
